In [29]:
#import required Libraries!
import pandas as pd
import numpy as np 
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.model_selection import RandomizedSearchCV,GridSearchCV
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import BaggingRegressor
from sklearn.svm import SVR
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error,r2_score
from sklearn.preprocessing import PolynomialFeatures
import warnings

<ul>
    <li type="I"><strong>Problem : Predicting Used Cars Prices Based Upon their Features : Based On India</strong></li>
    <ul><li>car_name</li></ul>
    <ul><li>brand</li></ul>
    <ul><li>model</li></ul>
    <ul><li>vehicle_age</li></ul>
    <ul><li>km_driven</li></ul>
    <ul><li>seller_type</li></ul>
    <ul><li>fuel_type</li></ul>
    <ul><li>transmission_type</li></ul>
    <ul><li>mileage</li></ul>
    <ul><li>engine</li></ul>
    <ul><li>max_power</li></ul>
    <ul><li>seats</li></ul>
    <ul><li>selling_price</li></ul>
</ul>


In [3]:
model_df = pd.read_csv("Data/transform.csv")
model_df

Audi A4  Audi A6  Audi A8  Audi Q7  BMW 3  BMW 5  BMW 6  BMW 7  BMW X1  \
0            0        0        0        0      0      0      0      0       0   
1            0        0        0        0      0      0      0      0       0   
2            0        0        0        0      0      0      0      0       0   
3            0        0        0        0      0      0      0      0       0   
4            0        0        0        0      0      0      0      0       0   
...        ...      ...      ...      ...    ...    ...    ...    ...     ...   
15405        0        0        0        0      0      0      0      0       0   
15406        0        0        0        0      0      0      0      0       0   
15407        0        0        0        0      0      0      0      0       0   
15408        0        0        0        0      0      0      0      0       0   
15409        0        0        0        0      0      0      0      0       0   

       BMW X3  ...  Petrol  Automatic  Manual  vehicle_age  km_driven  \
0           0  ...       1          0       1         0.75   1.750000   
1           0  ...       1          0       1        -0.25  -0.750000   
2           0  ...       1          0       1         1.25   0.250000   
3           0  ...       1          0       1         0.75  -0.325000   
4           0  ...       0          0       1         0.00  -0.500000   
...       ...  ...     ...        ...     ...          ...        ...   
15405       0  ...       1          0       1        -0.25  -1.019275   
15406       0  ...       1          0       1         0.75  -0.981925   
15407       0  ...       1          0       1        -1.00  -0.800000   
15408       0  ...       0          0       1         0.00   0.425000   
15409       0  ...       1          1       0        -1.00  -0.925000   

        mileage    engine  max_power     seats  selling_price  
0      0.005263 -1.174026  -0.974596 -0.402931         120000  
1     -0.135088 -0.132468  -0.150115 -0.402931         550000  
2     -0.468421 -0.132468  -0.196305 -0.402931         215000  
3      0.219298 -0.649351  -0.494226 -0.402931         226000  
4      0.543860  0.649351   0.233025 -0.402931         570000  
...         ...       ...        ...       ...            ...  
15405 -0.135088 -0.132468  -0.150115 -0.402931         545000  
15406  0.024561 -0.420779  -0.472286 -0.402931         250000  
15407 -0.380702  0.324675   0.060046  2.073801         925000  
15408  0.257895  0.649351   0.346882 -0.402931         425000  
15409 -0.292982  0.646753   0.672055 -0.402931        1200000  

[15410 rows x 290 columns]

In [4]:
model_df_org = pd.read_csv("Data/transform_org.csv")
model_df_org

Audi A4  Audi A6  Audi A8  Audi Q7  BMW 3  BMW 5  BMW 6  BMW 7  BMW X1  \
0            0        0        0        0      0      0      0      0       0   
1            0        0        0        0      0      0      0      0       0   
2            0        0        0        0      0      0      0      0       0   
3            0        0        0        0      0      0      0      0       0   
4            0        0        0        0      0      0      0      0       0   
...        ...      ...      ...      ...    ...    ...    ...    ...     ...   
15405        0        0        0        0      0      0      0      0       0   
15406        0        0        0        0      0      0      0      0       0   
15407        0        0        0        0      0      0      0      0       0   
15408        0        0        0        0      0      0      0      0       0   
15409        0        0        0        0      0      0      0      0       0   

       BMW X3  ...  Petrol  Automatic  Manual  vehicle_age  km_driven  \
0           0  ...       1          0       1            9     120000   
1           0  ...       1          0       1            5      20000   
2           0  ...       1          0       1           11      60000   
3           0  ...       1          0       1            9      37000   
4           0  ...       0          0       1            6      30000   
...       ...  ...     ...        ...     ...          ...        ...   
15405       0  ...       1          0       1            5       9229   
15406       0  ...       1          0       1            9      10723   
15407       0  ...       1          0       1            2      18000   
15408       0  ...       0          0       1            6      67000   
15409       0  ...       1          1       0            2      13000   

       mileage  engine  max_power  seats  selling_price  
0        19.70     796      46.30      5         120000  
1        18.90    1197      82.00      5         550000  
2        17.00    1197      80.00      5         215000  
3        20.92     998      67.10      5         226000  
4        22.77    1498      98.59      5         570000  
...        ...     ...        ...    ...            ...  
15405    18.90    1197      82.00      5         545000  
15406    19.81    1086      68.05      5         250000  
15407    17.50    1373      91.10      7         925000  
15408    21.14    1498     103.52      5         425000  
15409    18.00    1497     117.60      5        1200000  

[15410 rows x 290 columns]

In [5]:
data_dt = pd.read_csv("Data/Validation.csv")

In [22]:
x = model_df_org.iloc[:,0:289] 
y = model_df_org.iloc[:,[289]]

<h2><strong>Linear Regression</strong><h2>

In [50]:
#LinearRegression
x_train, x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=24)
lr = LinearRegression()
lr_fit = lr.fit(x_train,y_train)

In [51]:
pre = lr_fit.predict(x_test)
pre

array([[3706597.28000241],
       [ 244798.68222355],
       [2269547.37443978],
       ...,
       [ 506493.71352401],
       [ 610034.34940581],
       [ 633689.2356063 ]], shape=(3082, 1))

In [52]:
r2_score(y_test,pre)

0.785279587871063

<h2><strong>Decision Tree</strong><h2>

In [23]:
#DecisionTree
x_train, x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=24)
dt = DecisionTreeRegressor()
dt_train = dt.fit(x_train,y_train)
dt_train

DecisionTreeRegressor()

In [26]:
pred = dt_train.predict(x_test)

In [30]:
r2_score(y_test,pred)

0.8188395028128986

In [38]:
#Tuning dt using RandomizedCV
params = {
    'max_depth': [4, 5, 6, 8, 10, None],
    'min_samples_split': [2, 4, 6, 10],
    'min_samples_leaf': [1, 2, 4, 6],
    'max_features': ['auto', 'sqrt', 'log2', None]
}
random = RandomizedSearchCV(estimator=dt,param_distributions = params,cv=5,n_iter=20,random_state=12,n_jobs=-1,scoring="r2")
tune_dt = random.fit(x_train,y_train)
tune_dt

C:\Users\lipun\jupyterfix\Lib\site-packages\sklearn\model_selection\_validation.py:516: FitFailedWarning: 
30 fits failed out of a total of 100.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
13 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\lipun\jupyterfix\Lib\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\lipun\jupyterfix\Lib\site-packages\sklearn\base.py", line 1356, in wrapper
    estimator._validate_params()
  File "C:\Users\lipun\jupyterfix\Lib\site-packages\sklearn\base.py", line 469, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\lipun\jupyterfix\Lib\site-pac

RandomizedSearchCV(cv=5, estimator=DecisionTreeRegressor(), n_iter=20,
                   n_jobs=-1,
                   param_distributions={'max_depth': [4, 5, 6, 8, 10, None],
                                        'max_features': ['auto', 'sqrt', 'log2',
                                                         None],
                                        'min_samples_leaf': [1, 2, 4, 6],
                                        'min_samples_split': [2, 4, 6, 10]},
                   random_state=12, scoring='r2')

In [46]:
new_dt = DecisionTreeRegressor(min_samples_leaf=6)
new_dt_fit = new_dt.fit(x_train,y_train)
new_dt_fit

DecisionTreeRegressor(min_samples_leaf=6)

In [47]:
new_pred = new_dt_fit.predict(x_test)

In [48]:
#score
r2_score(y_test,new_pred)

0.8189437077258186

<h2><strong>RandomForest</strong><h2>

In [53]:
RandomF = RandomForestRegressor()
R_fit = RandomF.fit(x_train,y_train)
R_fit

C:\Users\lipun\jupyterfix\Lib\site-packages\sklearn\base.py:1363: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


RandomForestRegressor()

In [54]:
R_pre = R_fit.predict(x_test)
R_pre

array([6155000.        ,  385585.        , 4391400.        , ...,
        444610.        ,  507305.38600289,  575990.        ],
      shape=(3082,))

In [55]:
r2_score(y_test,R_pre)

0.9336244661296405

In [56]:
importance = R_fit.feature_importances_

array([3.66617216e-04, 1.65397114e-04, 1.70675062e-05, 9.38102266e-05,
       2.42931948e-04, 8.11340685e-04, 1.55025136e-04, 5.82464147e-04,
       2.15091671e-04, 2.83702072e-04, 4.69064667e-05, 2.64535354e-04,
       6.45262118e-05, 5.85924730e-04, 3.43016107e-05, 4.60706501e-06,
       3.47316831e-07, 1.64516565e-02, 1.10971709e-07, 2.24368295e-05,
       3.08595061e-05, 6.02998831e-05, 6.11753891e-05, 7.40457365e-06,
       1.47681304e-04, 2.85470641e-06, 2.33450845e-04, 6.42290345e-05,
       2.63364959e-05, 3.27848794e-05, 9.23655975e-06, 2.48106044e-06,
       3.09297246e-04, 9.63767275e-05, 4.80726475e-05, 5.20120651e-06,
       7.36901752e-05, 5.74243624e-06, 9.15990905e-05, 2.48432678e-05,
       8.16481783e-05, 2.08649007e-05, 6.23771918e-06, 3.87656301e-06,
       2.48341974e-04, 2.38187034e-05, 2.71897591e-04, 1.10061617e-05,
       9.22740341e-06, 1.74128891e-05, 9.53396579e-05, 3.39773404e-03,
       1.85261605e-05, 7.14201404e-05, 3.55237257e-05, 3.74897451e-06,
      

In [58]:
import joblib
joblib.dump(R_fit,"Models/UsedCarRandom_Forest_Model.pkl")

['UsedCarRandom_Forest_Model.pkl']

<h1><strong>Final Report: Model Predictions</strong></h1>

<li><b>Best Model:</b> RandomForestRegressor Gave r2 score of almost equal to 1 i.e 0.9336244661296405.This shows that it covers or explain 91%  variance across the dataset.
</li>